export enum CardTypePaymentBooking {
  AMEX = 'AMEX',
  EURO6000 = 'EURO6000',
  JCB = 'JCB',
  DINERS = 'DINERS',
  MASTERCARD = 'MASTERCARD',
  VISA = 'VISA',
  MAESTRO = 'MAESTRO',
  SWITCH = 'SWITCH',
  SOLO_GB = 'SOLO_GB',
  AIRPLUS = 'AIRPLUS',
  CHINAUNIONPAY = 'CHINAUNIONPAY',
  DISCOVER = 'DISCOVER',
}